### ISSUE TITLE
Option to download the files that have hits

### ISSUE THREAD

**Issue by mpopdam** [martijnspaan/GitHubSearch#6]
It would be nice to be able to download the files that have search hits so you can open them locally.

**Comment by martijnspaan** [comment]
The files are already downloaded in the local cache folder, is that enough?

**Comment by mpopdam** [comment]
I saw that indeed. But it would be nice if these files had a name by which you can see from what repository it originates.

**Comment by martijnspaan** [comment]
Ok, currently the name contains the ID of the repository, which can easily be changed to the name of the repository. So the cached filename will be:

{reponame}-{filename}-{commit-sha}.cache

Additionally it might be wise to also put files in a subfolder for the repo name, can become quite a big list this cache folder.
